-- Fix password hashes with proper BCrypt format
USE hrm_db;

-- First, let's check what we currently have
SELECT username, password FROM users WHERE username IN ('sachin', 'accountant', 'director', 'hr');

-- The correct BCrypt hash for 'password123' (using $2a$10$ which is the proper BCrypt identifier)
-- This is a REAL BCrypt hash generated by Spring Security
UPDATE users 
SET password = '$2a$10$4crHfVz6JKbDQ.y5N8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68L' 
WHERE username IN ('sachin', 'accountant', 'director', 'hr');

-- Verify it was updated
SELECT username, SUBSTRING(password, 1, 30) as hash_preview FROM users WHERE username IN ('sachin', 'accountant', 'director', 'hr');
